### ISSUE TITLE
hardcoded projectKey 

### ISSUE THREAD

**Issue by sshibani** [commercetools/sunrise-spa#157]
The projectKey is hardcoded for the scopes in the sunrise.config file.
When setting the projectKey as an env variable the scopes are not matching to the correct projectKey. 

https://github.com/commercetools/sunrise-spa/blob/master/sunrise.config.js#L10

**Comment by lauraluiz** [comment]
You must also include the scopes in your env variables. It is no longer an option like it was before. That's why the documentation explains that you should download or copy/paste the information coming from the MC (https://github.com/commercetools/sunrise-spa/blob/master/netlify.toml#L9). And with Netlify, now scope is mandatory if `projectKey` is set (https://github.com/commercetools/sunrise-spa/blob/master/netlify.toml#L9)

The reason why now it is mandatory is because the scope changes too often depending on the features you need, and if you don't select the exact scope for your client as it is provided in Sunrise SPA, your application is going to break.

That's why the best policy is to provide the scope, the same way you always provide the project key, the client secret and the client ID. It all belongs together.
