### ISSUE TITLE
"Add to Shopping Bag" button is not working on MacOSX + Chrome/Firefox

### ISSUE THREAD

**Issue by juansopenpay** [commercetools/sunrise-spa#260]
Hi,

When clicking on the "Add to Shopping Bag" on MacOSX on Chrome or Firefox the items are not added to the cart and the console throws the following error:

Error: GraphQL error: LineItem error: Tax category '3ffce334-981a-4f0f-bee2-a15ff97bd82b' is missing a tax rate for country 'GB'
    at new t (bundle.esm.js:63)
    at Object.next (bundle.esm.js:1004)
    at _ (Observable.js:135)
    at w (Observable.js:179)
    at e.value (Observable.js:235)
    at bundle.esm.js:866
    at Set.forEach (<anonymous>)
    at Object.next (bundle.esm.js:866)
    at _ (Observable.js:135)
    at w (Observable.js:179)
    
The button works fine only in Safari.

 My setup is the following:

-  MacOSX Big Sur 11.5.1
-  Chrome 92.0.4515.159 (Official Build) (x86_64) (Latest version)
-  Firefox 91.0.1 (64-bit)

Steps to reproduce:
- Add an item to the shopping cart in the following link: https://openpay.mldemo.co.uk/US/en/product/pinko-blazer-1B10ZP-black/M0E20000000DKN0
 
![Screenshot 2021-08-19 at 16 10 20](https://user-images.githubusercontent.com/62891779/130096416-78e9f402-43ef-40e1-b4c8-665f2302faa8.png)

**Comment by DanPerovich** [comment]
@juansopenpay:  The owner of the commercetools project associated with this frontend will need to configure a tax rate for the country 'GB' within the tax category shown '3ffce..'  This is not a sunrise-spa code issue, it is a configuration issue within the environment you are trying to use "openpay.mldemo.co.uk".

**Comment by harm-meijer** [comment]
@juansopenpay I can see that you set up UK as a country in [sunrise.config.js](https://github.com/commercetools/sunrise-spa/blob/master/sunrise.config.js#L40) but it's missing a [currency entry](https://github.com/commercetools/sunrise-spa/blob/master/sunrise.config.js#L45-L51) so when you [select the country](https://github.com/commercetools/sunrise-spa/blob/master/src/components/header/TheHeader/TheHeader.vue#L26-L31) no products will be listed because a currency is mandatory when querying for products as the sunrise spa project uses [price selection](https://docs.commercetools.com/api/projects/products#price-selection).

I am back from holiday so if you need any help I'll be available, please let me know if you need any further assistance.
