### ISSUE TITLE
When attempting to reset password flow we see an error about manage_customers

### ISSUE THREAD

**Issue by paulcrussell** [commercetools/sunrise-spa#267]
Its a 403 response with the following

{
  "statusCode": 403,
  "message": "Insufficient scope. One of the following scopes is missing: manage_customers.",
  "errors": [
    {
      "code": "insufficient_scope",
      "message": "Insufficient scope. One of the following scopes is missing: manage_customers."
    }
  ],
  "error": "insufficient_scope",
  "error_description": "Insufficient scope. One of the following scopes is missing: manage_customers."
}

**Comment by harm-meijer** [comment]
Normally the reset password logic should be implemented on your server but in the demo it is done in client side code. The scope for client side does not include `manage_customers` because that would enable anyone to change anyones account. You can add `manage_customers` scope when you create the [api client](https://docs.commercetools.com/merchant-center/api-clients#create-an-api-client).

More info on how the reset password works can be found [here](https://github.com/commercetools/sunrise-spa/blob/development/Docs/Readme.md#forgot-password)
